# Generated by Django 5.2.6 on 2025-09-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_adminpageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='worker_response',
            field=models.CharField(choices=[('pending', 'Awaiting Response'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
