# Generated by Django 5.2.6 on 2025-09-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_booking_worker_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
